[ci] Add check for bazel lock file

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -33,3 +33,12 @@ jobs:
       - name: Buildifier check
         run: |
           bazelisk run //quality:buildifier_check
+
+      - name: Check Bazel lock file
+        run: |
+          bazelisk mod deps
+          if ! git diff --exit-code MODULE.bazel.lock; then
+            echo "::error::MODULE.bazel.lock is not up to date"          >&2
+            echo "Regenerate this lock file using \`bazelisk mod deps\`" >&2
+            exit 1
+          fi
